### ISSUE TITLE
nerdctl fails to build for dockerfiles with full path

### ISSUE THREAD

**Issue by seemethere** [containerd/nerdctl#206]
`nerdctl` installed with rootless containerd and buildkit fails to build dockerfiles when the dockerfile specified is a full path:

# Simple Repro
Create test Dockerfile in your root directory (`Dockerfile`):
```dockerfile
FROM alpine
RUN apk -U add curl
```

Run the following
```shell
$ nerdctl build -f $(realpath Dockerfile) .
[+] Building 0.1s (2/2) FINISHED                                                                                                                          
 => [internal] load build definition from /tmp/tmp.gdczD7DusJ/Dockerfile                                                                             0.1s
 => => transferring dockerfile: 2B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                    0.1s
 => => transferring context: 2B                                                                                                                      0.0s
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount044783237/tmp/tmp.gdczD7DusJ/Dockerfile: no such file or directory
FATA[0000] unrecognized image format   
```

**Comment by fahedouch** [comment]
Actually we don't support this 

https://github.com/containerd/nerdctl/blob/3668d7d0c2e8712ddf295622ed683f69651d023c/build.go#L147

The dockerfile context is the same as the build context.
I will fix this.

Have a Nice day

**Comment by andel7** [comment]
Was this fixed - can't build image from Dockerfiles with the same error

**Comment by pmmlo** [comment]
@andel7 This sounds stupid, but try running the build command at least 3 times after failure (if you know the Dockerfile works with Docker/docker CLI).  For me, it progresses a little further each time until it succeeds in building a new Dockerfile.

**Comment by AkihiroSuda** [comment]
Already fixed in nerdctl v0.8.2:
- https://github.com/containerd/nerdctl/pull/207


I also tested v0.19.0 locally and I don't see any regression.

**Comment by AkihiroSuda** [comment]
@andel7 Are you seeing this error with Lima/Colima/Rancher Desktop?
If so, please make sure that your Dockerfile is located under `/Users` or any directory that is exposed to Lima.

**Comment by Cerebus** [comment]
> @andel7 Are you seeing this error with Lima/Colima/Rancher Desktop? If so, please make sure that your Dockerfile is located under `/Users` or any directory that is exposed to Lima.

Yes, and yes it is, but still getting this error.

nerdctl version 0.20.0

**Comment by Cerebus** [comment]
Oh, nevermind.  The problem was between the keyboard and the chair.

**Comment by ArVar** [comment]
I have a very similar issue:
` => [internal] load build definition from Dockerfile                                                              0.0s 
 => => transferring dockerfile: 2B                                                                                0.0s 
 => [internal] load .dockerignore                                                                                 0.0s 
 => => transferring context: 2B                                                                                   0.0s 
error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount3778739720/Dockerfile: no such file or direc
tory
FATA[0000] unrecognized image format`

I'm pretty sure, there is something going wrong in passing the data from the context to the builder, i.e. the Dockerfile.
Using Rancher Desktop on windows 10 with WSL2 Ubuntu.
