### ISSUE TITLE
Unable to create a container (`name "NAME” is already used by ID …`)

### ISSUE THREAD

**Issue by yikyo** [containerd/nerdctl#499]
If I run the following command, it prompts

```
FATA[0000] name "adguardhome" is already used by ID "a1e09c7badd41dd267050f3edeb16c9d6dabf5762fcbfc481eb1ae01ae34e64d"
```

```
sudo nerdctl run --name adguardhome\
    --restart always\
    -v /home/yikyo/application/adguardhome/work:/opt/adguardhome/work\
    -v /home/yikyo/application/adguardhome/conf:/opt/adguardhome/conf\
    -p 53:53/tcp\
    -p 53:53/udp\
    -p 3000:3000/tcp\
    -d adguard/adguardhome:v0.106.3
```

But running "nerdctl ps -a" doesn't show it, and it can't be deleted

```
uname -a
Linux vyos 5.4.156-amd64-vyos #1 SMP Thu Oct 28 18:19:14 UTC 2021 x86_64 GNU/Linux

sudo nerdctl version

Client:
 Version:	v0.13.0
 Git commit:	08792cc09464b13b4fe97ca1bf06a9ac3e696fde

Server:
 containerd:
  Version:	v1.5.7
  GitCommit:	8686ededfc90076914c5238eb96c883ea093a8ba
```

**Comment by AkihiroSuda** [comment]
Please try removing /var/lib/nerdctl/1935db59/names/default/adguardhome

**Comment by yikyo** [comment]
Thanks, it has been solved

But still can't create the container, there are some other problems, I'll look for other solutions

thanks

**Comment by akshayjai1** [comment]
Did anyone find solution for this?

**Comment by vinok88** [comment]
First, use `nerdctl rm <name>` to remove the existing container.

**Comment by LanceSandino** [comment]
I'm running into this issue after running some docker compose commands.

**Comment by daogilvie** [comment]
Just leaving a comment here to say this solution worked for me, but I had to hunt around for the name file as it wasn't in the path given above. I ended up finding it in `~/.local/share/nerdctl/1935db59/names/default/`

**Comment by veleek** [comment]
Has anybody running on Windows been able to figure this out?  I've dug around in `C:\users\<user>\AppData\Local` for something that looked similar but couldn't find anything and I'm still seeing this even after uninstalling and reinstalling.

**Comment by veleek** [comment]
Was able to figure this out on my own.  You can fix this by launching the rancher desktop WSL instance (`wsl -d rancher-desktop`) and THEN browsing to the path @AkihiroSuda specified.  

```
/var/lib/nerdctl/<id>/name/default/<name>
```

It might also be worthwhile to remove the associated container in 

```
/var/lib/nerdctl/<id>/containers/default/<containerid>
```

**Comment by junnplus** [comment]
Maybe fix by https://github.com/containerd/nerdctl/pull/1151

**Comment by fahedouch** [comment]
fixed by https://github.com/containerd/nerdctl/pull/1151

**Comment by codingbycoding** [comment]
find /var/lib/nerdctl -name your-container-name
then remove the file

**Comment by BuddhiAbeyratne** [comment]
Hey @fahedouch we are running the latest version on ubuntu on some of our IOT devices 
This is version 1.7.7
The issue still persists. we made a hot fix with @codingbycoding running in a health checker on our host

**Comment by fahedouch** [comment]
> with

Hi @BuddhiAbeyratne, could you please share your hotfix in the upstream nerdctl repo. thanks

**Comment by apostasie** [comment]
@AkihiroSuda namestore concurrency issue have been fixed.

Suggesting we close.

**Comment by finopay1255-art** [comment]
> Please try removing /var/lib/nerdctl/1935db59/names/default/adguardhome

Goated solution, worked for me.
